# Generated by Django 5.2.4 on 2025-08-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_messagecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='auteur',
            field=models.CharField(default='inconnu', max_length=100),
        ),
    ]
