# Generated by Django 5.2.4 on 2025-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_article_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(max_length=100),
        ),
    ]
