# Generated by Django 5.2.4 on 2025-08-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_article_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nombre_vues',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
