# Generated by Django 5.2.4 on 2025-08-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_article_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
