# Generated by Django 5.2.4 on 2025-08-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_article_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('image_principal', models.ImageField(upload_to='Services/')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('Categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pages.categorie')),
            ],
        ),
    ]
