# Generated by Django 5.2.4 on 2025-08-05 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_imageservice_servicecategorie_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Categorie',
        ),
        migrations.AddField(
            model_name='service',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
