# Generated by Django 5.2.4 on 2025-08-05 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_service_categorie_service_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.categorie'),
        ),
    ]
