# Generated by Django 5.2.4 on 2025-08-05 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_service_categorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_principal',
        ),
        migrations.AddField(
            model_name='service',
            name='image_principale',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.categorie'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
