# Generated by Django 5.2.4 on 2025-08-05 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_service_image_principal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('reponse', models.TextField()),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (plus petit en premier)")),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq', to='pages.service')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
